---
title: "JavaScript; the omnipotent"
author: L Hama
date: '`r Sys.Date()`'
output: revealjs::revealjs_presentation
reveal_options:
      slideNumber: true
bibliography: refs.bib
---

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

# JavaScript
<blockquote class="twitter-tweet" data-lang="en-gb"><p lang="en" dir="ltr"><a href="https://t.co/ygYakEfRbF">https://t.co/ygYakEfRbF</a><br><br>As official as it gets. <a href="https://t.co/hKwFRAZayx">pic.twitter.com/hKwFRAZayx</a></p>&mdash; BrendanEich (@BrendanEich) <a href="https://twitter.com/BrendanEich/status/1087911921876004865?ref_src=twsrc%5Etfw">23 January 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

## Why JS?

- The bad reputation? 

> "Saving the world wide web from vulnerable JavaScript
"

- Is it?

<blockquote style="margin:auto" class="twitter-tweet" data-lang="en-gb"><p lang="en" dir="ltr">Think of JavaScript as a Dante-like figure, moving from the Netscape rush-job dynamic language hell of the &#39;90s to paradise. Programming Language Theory is Virgil. I won&#39;t make more analogies that put real people in circles of hell (but I could!). Anyway, no: JS is not the devil.</p>&mdash; BrendanEich (@BrendanEich) <a href="https://twitter.com/BrendanEich/status/1124292439358025728?ref_src=twsrc%5Etfw">3 May 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 


## Why JS?

- Machine Learning (TensorFlow.js)
- Scientific/information visualization
- Development (VS Code - Microsoft, Atom - github)
- ReactJS (Facebook), Angular (Google/Microsoft) etc.
- ReactNative (Develop smartphone apps - native)

## JS intro
```{js}
document.write("<p style='color:orange'>Hello World</p>");
```

- Open the Markdown document within the repo.
- We will get back to the slides from time time.

## JS document
<p class="box">Tip: use the inspect element to find whiwhc table you like to add the new row/td to.</p>


## JS Goodies
> https://github.com/getify/You-Dont-Know-JS

> https://github.com/sorrycc/awesome-javascript

<style>
.box {
    border-radius: 3px;
    position: relative;  /*  <--- */
    font-style: italic;
    text-align: center;
    padding: 1rem 1.2rem;
    width: 80%;  /* create space for the quotes */
    color: #4a4a4a;
    margin: 1rem auto 2rem;
    color: #4a4a4a;
    background: #E8E8E8;
}
/* -- create the quotation marks -- */
.box:before,
.box:after{
    font-family: FontAwesome;
    position: absolute;
    /* -- inside the relative position of blockquote -- */
    top: 13px;
    color: #E8E8E8;
    font-size: 34px;
}
.box:before{
    content: "\f10d";
    margin-right: 13px;
    right: 100%;
}
.box:after{
    content: "\f10e";
    margin-left: 13px;
    left: 100%;  
}
</style>